export const STORE_LOGIN_MICROSOFT = 'STORE_LOGIN_MICROSOFT';
export const STORE_LOGIN_API_DATA = 'STORE_LOGIN_API_DATA';
export const SET_LOGOUT_SPINNER = 'SET_LOGOUT_SPINNER';
export const STORE_NOTIFICATIONS_LIST = 'STORE_NOTIFICATIONS_LIST';

